### ISSUE TITLE
css-reset and css-normalize should not be used in one project

### ISSUE THREAD

**Issue by gssxgss** [yuhiisk/starter-kit#1]
CSS Reset:

> "The goal of a CSS Reset Stylesheet is to reduce browser inconsistencies in things like default line heights, margins and font sizes of headings, etc."

CSS Normalize:

> "Normalize.css makes browsers render all elements more consistently and in line with modern standards."

[What is the difference between Normalize.css and Reset CSS?](http://stackoverflow.com/questions/6887336/what-is-the-difference-between-normalize-css-and-reset-css)

```
// config.sass
$to-normalize: true

// style.sass
@if $to-normalize
  @import normalize
@else
  @import reset
```

**Comment by yuhiisk** [comment]
Thank you.

```
// config.sass
$to-normalize: true

// style.sass
@if $to-normalize
  @import normalize
@else
  @import reset
```

It is an error in this reading.
`Error: Import directives may not be used within control directives or mixins.`

The study was a result, I was disconnect the use of `normalize.css` and `reset.css`.
Also I have prepared the option of "html5doctor" and "Eric Meyer reset" and "YUI 3 reset" and "Normalize" and "Original reset".

```
config/_config.scss

// "html5doctor", "ericmeyer", "yui", "normalize", "original"
$resetCSS: "original";
```
