### ISSUE TITLE
Separate sass task and compass task

### ISSUE THREAD

**Issue by hystking** [yuhiisk/starter-kit#10]
coffee and browserify are separated.
So, styles task should be separated too.

**Comment by yuhiisk** [comment]
We've split the style task.

![寿司ゆき:cool](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/09.png)

**Comment by yuhiisk** [comment]
However, this still has a corresponding of this problem, there is a bug.

[The new browser support features in Compass 1.x](http://atendesigngroup.com/blog/new-browser-support-features-compass-1x)
