### ISSUE TITLE
EventDispatcher not working.

### ISSUE THREAD

**Issue by hystking** [yuhiisk/starter-kit#3]
https://github.com/yuhiisk/starter-kit/blob/master/src/coffee/EventDispatcher.coffee#L54-55
for..in loop syntax of coffeescript differ from javascript's syntax.

It should be

```
for i in copyEvents
  i.apply(opt_this || @, arg)
```

or

```
for i of copyEvents
  copyEvents[i].apply(opt_this || @, arg)
```

**Comment by yuhiisk** [comment]
OK! Fixed.
