### ISSUE TITLE
スターターキットの未来について

### ISSUE THREAD

**Issue by hystking** [yuhiisk/starter-kit#32]
ちょっと思ったんですが、
僕が周りに軽く聞いただけでも、スターターキットってそんな使われてなくて、
かくいう僕も、使ってなくて、
別にそれが悪いわけじゃないんですが、
なんか、明確にスターターキットの立ち位置を定めたほうがいいなと思っています。

今のファイ部の仕組み上、
やっぱり、1人でやるぶんには、オレオレテンプレート使ったほうが、効率がいいのは当然だと思っていて、
かと言って、2人以上でやるとき、スターターキットを使うと超便利かというと、別にそうでもないなと思っています。

自分でテンプレートを用意してるような人は、コマンドを1行叩けば、必要な機能は動くように作ってるから、
別に他人のテンプレートだろうと、苦労することは少ないし、
テンプレートの作成主が案件から手離れすることも稀なので、メンテできなくて辛いってこともあまりないです。
## 

なので、「じゃあ、スターターキットの立ち位置って何よ」ってなると、
効率化よりは、例示になるのかなと思っています。

例示というのは、1つは、Gulpやnodeの使い方の例示。
これは単にお手本用として、勉強用としての役割。

もう1つは、カヤックのフロント案件のスタンダードの例示。
これは、ファイ部では、こんな感じのスタイル（Jadeだったり、Sassだったり）で仕事を進めることが多いということを示して、
趣味でしかマークアップをしてこなかった人には、OGの書き方だったり、viewportだったり、IE8避けの魔法の呪文だったりを教える役割。
## 

とどのつまり、何が言いたいかというと、
今のスターターキット、全然スターターじゃないし、Fatすぎるから、機能ガリガリ削ったほうがいい。

そして、できるなら、コメントを増やして、初学者に優しい風にしたい。

<pre>meta(http-equiv="X-UA-Compatible", content="IE=edge")</pre>

の隣に

<pre>meta(http-equiv="X-UA-Compatible", content="IE=edge") // これは、IEでのバグを避けるためのタグ</pre>

と書かれているだけで、全然違うと思うんですよね。

**Comment by hystking** [comment]
誤爆しました
許して

**Comment by yuhiisk** [comment]
OK, @hystking .
ありがとう、キミの言いたいことはよーくわかった。

スターターキットの方向性に関しては決めなければいけないと思っていた。
パッケージの導入が多くなって、設定も多くなって、気がついたら気楽に始めようにも今ではかなりの時間と労力が必要だ。
初心者には複雑で全くもって優しくない。
それに効率化になっているかどうかについてもひしひしと感じていた。今までこうゆうものを作る人達を見ていても、なかなか流行らないで廃れていく。まぁそうゆう運命なのかもと。人それぞれ好みはあるし、足並み揃えて使っていこうぜ、となるには役不足だろうともね。

最近のフロント最前線で使えるスターターキットにするには無理だと感じた。そしてそれに近しいものがすでに世の中にはある。キミの言うとおり周りに例示する目的で舵を切ったほうが得策かもしれない。いや、そうするべきだろう。

ぼくはもうカヤックのためにスターターキットを作っているわけではなくて、今や自分のためのプロジェクトである。これからはカヤックに依存しないプロジェクトにしようと思っているが、キミの意見を参考に考えさせてもらおう。とはいえ、使ってもらえるというのはうれしいことだから、舵切りの件は前向きに検討したいと思う。教育に対して効率的になる可能性は大いにある。

まさかイブの夜にスターターキットを議論することになるとはな。

**Comment by hystking** [comment]
すみませんカヤックのほうに書こうとして誤爆しました

**Comment by hystking** [comment]
返信ありがとうございます。
すみません、こっちのプライベートリポジトリにforkしていて、それと間違えたのです。。。
でも、方向性うんぬんについては、実際、世の似たようなテンプレートに関しては、同じような問題を抱えてるのかもしれないですね。
実際、Yeomanがフェードアウトした（僕の中ではそういうイメージです）のを見ると、難しいんだろうなと。

なんかよく分からない日に付き合わせて、すみません。
🎄🍴⛄🎁 Happy Holiday! ❄🎅👪🔔
